language: python
python:
  - "3.8"
  - "pypy3"

env:
  - KV_DB=redis
  - KV_DB=redis ovs_version=2.9.5
 
services:
  - docker
  
cache:
  directories:
    - cache
    
# command to run tests
script: sudo -H bash -xe ci_test.sh


