language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "pypy3.5"

env:
  - KV_DB=redis
  - KV_DB=redis ovs_version=2.9.3
 
services:
  - docker
  
cache:
  directories:
    - cache
    
# command to run tests
script: sudo -H bash -xe ci_test.sh


