language: python
sudo: required
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

 
services:
  - docker
  
cache:
  directories:
    - cache
    
# command to run tests
script: sudo -H bash -xe ci_test.sh


