# from ubuntu 16.04 , apt-get will get ovs 2.5
FROM ubuntu:16.04

MAINTAINER gpl

# update source , install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
                              openvswitch-switch \
                              wget \
                              curl \
                              iproute2 \
                              iputils-ping \
                              isc-dhcp-client \
                              pypy \
                   && rm -rf /var/lib/apt/lists/* 

# install pip
#
# because supervisor don't support python3
# so should install supervisor in python2
RUN if [ ! -e /usr/local/bin/pip2.7 ]; then : \
         && wget  --no-check-certificate -O /tmp/get-pip.py 'https://bootstrap.pypa.io/get-pip.py' \
         && pypy /tmp/get-pip.py \
         && rm /tmp/get-pip.py \
         && pip2.7 install supervisor \
         && pip2.7 install coverage \
    ; fi


# link python interpreter to same 
RUN ln -sf $(which pypy) /opt/python && ln -sf $(which pip2.7) /opt/pip \
                                        && ln -sf $(which coverage) /opt/coverage  

CMD ["/bin/bash"]
