# from ubuntu 16.04 , apt-get will get ovs 2.5
FROM ubuntu:16.04

MAINTAINER gpl

# update source , install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
                              openvswitch-switch \
                              wget \
                              curl \
                              iproute2 \
                              iputils-ping \
                              isc-dhcp-client \
                              python3 \
                   && rm -rf /var/lib/apt/lists/* 

# install pip
#
# because supervisor don't support python3
# so should install supervisor in python2
RUN if [ ! -e /usr/local/bin/pip2.7 ]; then : \
         && wget  --no-check-certificate -O /tmp/get-pip.py 'https://bootstrap.pypa.io/get-pip.py' \
         && python2.7 /tmp/get-pip.py \
         && pip2.7 install supervisor \
    ; fi


RUN if [ ! -e /usr/local/bin/pip3 ]; then : \
         && python3 /tmp/get-pip.py \
         && rm /tmp/get-pip.py \
         && pip3 install coverage \
    ; fi  

# link python interpreter to same 
RUN ln -sf $(which python3) /opt/python && ln -sf $(which pip3) /opt/pip \
                                        && ln -sf $(which coverage) /opt/coverage  

CMD ["/bin/bash"]
